### ISSUE TITLE
Can't view metadata contact details in (full view)

### ISSUE THREAD

**Issue by jonescc** [metadata101/iso19115-3.2018#50]
You can add/edit/delete metadata contacts (organisations/individuals and organisation individuals), but you can't view them in full view:

![image](https://user-images.githubusercontent.com/1860215/76060108-a722c280-5fd4-11ea-9fce-14a3591e4efa.png)

![image](https://user-images.githubusercontent.com/1860215/76060127-b144c100-5fd4-11ea-959c-53ff551279ff.png)

**Comment by fxprunayre** [comment]
Could you post the XML for testing ? I can't reproduce.

**Comment by jonescc** [comment]
Works in master
