### ISSUE TITLE
Can't view temporal resolution

### ISSUE THREAD

**Issue by jonescc** [metadata101/iso19115-3.2018#51]
Can enter a temporal resolution when editting

![image](https://user-images.githubusercontent.com/1860215/76060260-f49f2f80-5fd4-11ea-92a5-a6a2a06588b0.png)

But you can't view it:

![image](https://user-images.githubusercontent.com/1860215/76060277-fe289780-5fd4-11ea-8a91-055d0e547fba.png)

**Comment by fxprunayre** [comment]
Are you looking into it ? I can also have a look if needed.

**Comment by jonescc** [comment]
I'm not around next week and we're still testing...  Will look at what we can fix when I get back (I'm assuming view issues won't be hard to sort out).  Some help would be good?

**Comment by jonescc** [comment]
Editing looks pretty solid so far, although I think we had some issues with sample dimension elements.
