### ISSUE TITLE
Can't view Data Quality information

### ISSUE THREAD

**Issue by jonescc** [metadata101/iso19115-3.2018#52]
You can edit/modify/delete all used data quality elements/attributes but there's no data quality tab/elements displayed when viewing the record in full view.

![image](https://user-images.githubusercontent.com/1860215/76060372-3cbe5200-5fd5-11ea-8ee9-eeb206716eba.png)

![image](https://user-images.githubusercontent.com/1860215/76060386-447df680-5fd5-11ea-858e-32f0e6106cc3.png)

**Comment by fxprunayre** [comment]
Could you post the record for testing ?

**Comment by jonescc** [comment]
Works in master
